#! /usr/bin/python
################################################################################
#	scripts/fixdeps.py
#
#	Fix dependency files generated by GCC
#	Inspired by http://mad-scientist.net/make/autodep.html but written from
#	scratch.
#
#	Copyright (C) 2013 Paul Barker, Loughborough University
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
################################################################################

import sys
import shutil

source_name = sys.argv[1]
target_name = sys.argv[2]

source = open(source_name, 'r')
target = open(target_name, 'w')

# Copy source to target and rewind source
shutil.copyfileobj(source, target)
source.seek(0)

# Add a newline incase the source file didn't end with one
target.write('\n')

for line in source:
	# Drop anything to the left of a colon
	if ':' in line:
		line = line.split(':', 1)[1]

	# Split into dependencies
	for dep in line.split():
		# Ignore single backslash
		if not dep == '\\':
			# Write dependency as a target
			target.write(dep + ':\n')
